### ISSUE TITLE
Choose between <double-qoutes> or <single-qoutes>

### ISSUE THREAD

**Issue by joykare** [AndelaOSP/andela-societies-frontend#18]
### Description 
We have both double and single qoutes instances in the project 
 
### How done looks like
- Choose one standard
- Change all instances of the other
- Add eslint rule to enforce qoute-rules

**Comment by john555** [comment]
@joykare We have single quotes enforced for all strings. Would you care to shade more light on where double quotes were used for strings?

**Comment by joykare** [comment]
@john555 I mean that we have instances where we have double quotes and single quotes.


Sprint planning: Use `double-quotes`. Have eslint flag single-quotes
